# Generated by Django 4.2.6 on 2024-01-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
