# Generated by Django 4.2.6 on 2023-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerpreferencedetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprefarencedetails',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerprefarencedetails',
            name='education',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerprefarencedetails',
            name='occupation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerprefarencedetails',
            name='partner_expectations',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerprefarencedetails',
            name='residency_status',
            field=models.CharField(max_length=255),
        ),
    ]
