# Generated by Django 4.2.6 on 2023-10-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoroscopeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moon_sign', models.CharField(max_length=150)),
                ('star', models.CharField(max_length=150)),
                ('gotra', models.CharField(max_length=150)),
                ('manglik', models.CharField(max_length=150)),
                ('shani', models.CharField(max_length=150)),
                ('hororscope_match', models.CharField(max_length=150)),
                ('place_of_birth', models.CharField(max_length=150)),
                ('place_of_country', models.CharField(max_length=255)),
                ('hours', models.CharField(max_length=255)),
                ('minitues', models.CharField(max_length=255)),
                ('seconds', models.CharField(max_length=255)),
                ('am_pm', models.CharField(max_length=255)),
            ],
        ),
    ]
