# Generated by Django 4.2.6 on 2023-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Mobile_Number',
            field=models.CharField(max_length=255),
        ),
    ]
