# Generated by Django 4.2.6 on 2023-12-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0006_alter_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(default='2023-12-04', max_length=10),
        ),
    ]
