# Generated by Django 4.2.6 on 2024-01-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapi', '0008_alter_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(default='2024-01-11', max_length=10),
        ),
    ]
